#!/usr/bin/env python3
"""One-off migration script: rename old iOS album directories to new layout.

Old layout:
    orig-heic/  rendered-heic/  combined-heic/  combined-jpeg/
    orig-mov/   rendered-mov/   combined-mov/

New layout:
    ios/orig-img/  ios/edit-img/  main-img/  main-jpg/
    ios/orig-vid/  ios/edit-vid/  main-vid/

main-img/ and main-vid/ are NOT created by this script — run
`photree album optimize-all` after migration to regenerate them.

Usage:
    python migrate-albums.py <base-dir>           # dry run (default)
    python migrate-albums.py <base-dir> --apply   # actually rename
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

# Directories to move under ios/
MOVE_TO_IOS = {
    "orig-heic": "orig-img",
    "rendered-heic": "edit-img",
    "orig-mov": "orig-vid",
    "rendered-mov": "edit-vid",
}

# Directories to delete (will be regenerated by optimize)
DELETE = ("combined-heic", "combined-mov")

# Directories to rename in place
RENAME = {"combined-jpeg": "main-jpg"}


def find_ios_albums(base_dir: Path) -> list[Path]:
    """Find albums that have the old directory layout."""
    return sorted(
        Path(dirpath)
        for dirpath, dirnames, _ in os.walk(base_dir)
        if any(d in dirnames for d in ("orig-heic", "orig-mov"))
    )


def migrate_album(album_dir: Path, *, dry_run: bool) -> int:
    """Migrate a single album. Returns the number of actions taken."""
    actions = 0
    ios_dir = album_dir / "ios"

    # Create ios/ subdirectory
    if not ios_dir.is_dir():
        print(f"  mkdir  {ios_dir}")
        if not dry_run:
            ios_dir.mkdir(parents=True, exist_ok=True)
        actions += 1

    # Move directories under ios/
    for old_name, new_name in MOVE_TO_IOS.items():
        src = album_dir / old_name
        dst = ios_dir / new_name
        if src.is_dir():
            print(f"  move   {src} -> {dst}")
            if not dry_run:
                shutil.move(str(src), str(dst))
            actions += 1

    # Delete directories that will be regenerated
    for name in DELETE:
        d = album_dir / name
        if d.is_dir():
            file_count = sum(1 for _ in d.iterdir())
            print(f"  delete {d} ({file_count} files)")
            if not dry_run:
                shutil.rmtree(d)
            actions += 1

    # Rename in place
    for old_name, new_name in RENAME.items():
        src = album_dir / old_name
        dst = album_dir / new_name
        if src.is_dir():
            print(f"  rename {src} -> {dst}")
            if not dry_run:
                src.rename(dst)
            actions += 1

    return actions


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    base_dir = Path(sys.argv[1]).resolve()
    dry_run = "--apply" not in sys.argv

    if not base_dir.is_dir():
        print(f"Error: {base_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    albums = find_ios_albums(base_dir)
    if not albums:
        print(f"No albums with old layout found under {base_dir}")
        sys.exit(0)

    mode = "DRY RUN" if dry_run else "APPLYING"
    print(f"[{mode}] Found {len(albums)} album(s) under {base_dir}\n")

    total_actions = 0
    for album in albums:
        print(f"{album.relative_to(base_dir)}:")
        actions = migrate_album(album, dry_run=dry_run)
        if actions == 0:
            print("  (nothing to do)")
        total_actions += actions
        print()

    print(f"Total: {total_actions} action(s)")
    if dry_run:
        print("\nThis was a dry run. Re-run with --apply to execute.")
        print("After migration, run: photree album optimize-all")


if __name__ == "__main__":
    main()
