"""Filesystem protocol, repository, and helpers for photree albums."""

from .fileutils import (
    count_unique_media_numbers,
    display_path,
    file_ext,
    list_files,
    matching_subdirectories,
)
from .ios import (
    PICTURE_PRIORITY_EXTENSIONS,
    dedup_media_dict,
    find_files_by_number,
    find_files_by_stem,
    img_number,
    pick_media_priority,
)
from .media import (
    dedup_media_dict as generic_dedup_media_dict,
    find_files_by_key,
    group_by_key,
)
from .protocol import (
    ALBUM_DATE_RE,
    ALBUM_ID_PREFIX,
    ALBUM_YAML,
    CONVERT_TO_JPEG_EXTENSIONS,
    COPY_AS_IS_TO_JPEG_EXTENSIONS,
    DEFAULT_MEDIA_SOURCE,
    GALLERY_YAML,
    IMG_EXTENSIONS,
    IOS_DIR_PREFIX,
    IOS_IMG_EXTENSIONS,
    IOS_VID_EXTENSIONS,
    PHOTREE_DIR,
    SELECTION_DIR,
    SHARE_SENTINEL,
    SIDECAR_EXTENSIONS,
    STD_DIR_PREFIX,
    VID_EXTENSIONS,
    AlbumMetadata,
    AlbumShareLayout,
    GalleryMetadata,
    LinkMode,
    MediaSource,
    MediaSourceType,
    ShareDirectoryLayout,
    _ALBUM_DATE_RE,
    _BaseModel,
    _DATE_PART,
    _KeyFn,
    _stem_key,
    _to_kebab,
    format_album_external_id,
    format_external_id,
    generate_album_id,
    ios_media_source,
    MAIN_MEDIA_SOURCE,
    parse_album_year,
    parse_external_id,
    std_media_source,
)
from .repo import (
    delete_files,
    discover_albums,
    discover_browsable_media_files,
    discover_media_sources,
    discover_potential_albums,
    has_media_sources,
    is_album,
    load_album_metadata,
    load_gallery_metadata,
    move_files,
    resolve_gallery_dir,
    resolve_gallery_metadata,
    resolve_link_mode,
    save_album_metadata,
    save_gallery_metadata,
)

__all__ = [
    # fileutils
    "count_unique_media_numbers",
    "display_path",
    "file_ext",
    "list_files",
    "matching_subdirectories",
    # ios (iOS-specific convenience wrappers)
    "PICTURE_PRIORITY_EXTENSIONS",
    "dedup_media_dict",
    "find_files_by_number",
    "find_files_by_stem",
    "img_number",
    "pick_media_priority",
    # media (generic matching)
    "find_files_by_key",
    "generic_dedup_media_dict",
    "group_by_key",
    # protocol — enums
    "AlbumShareLayout",
    "LinkMode",
    "ShareDirectoryLayout",
    "SHARE_SENTINEL",
    # protocol — constants
    "ALBUM_DATE_RE",
    "ALBUM_ID_PREFIX",
    "ALBUM_YAML",
    "CONVERT_TO_JPEG_EXTENSIONS",
    "COPY_AS_IS_TO_JPEG_EXTENSIONS",
    "DEFAULT_MEDIA_SOURCE",
    "GALLERY_YAML",
    "IMG_EXTENSIONS",
    "IOS_DIR_PREFIX",
    "IOS_IMG_EXTENSIONS",
    "IOS_VID_EXTENSIONS",
    "PHOTREE_DIR",
    "SELECTION_DIR",
    "SIDECAR_EXTENSIONS",
    "STD_DIR_PREFIX",
    "VID_EXTENSIONS",
    # protocol — models
    "AlbumMetadata",
    "GalleryMetadata",
    "_BaseModel",
    "_to_kebab",
    # protocol — media source
    "_KeyFn",
    "_stem_key",
    "MediaSource",
    "MediaSourceType",
    "ios_media_source",
    "std_media_source",
    "MAIN_MEDIA_SOURCE",
    # protocol — external IDs
    "format_album_external_id",
    "format_external_id",
    "generate_album_id",
    "parse_external_id",
    # protocol — album naming
    "_ALBUM_DATE_RE",
    "_DATE_PART",
    "parse_album_year",
    # repo — metadata I/O
    "load_album_metadata",
    "save_album_metadata",
    "save_gallery_metadata",
    "load_gallery_metadata",
    # repo — gallery resolution
    "resolve_gallery_dir",
    "resolve_gallery_metadata",
    "resolve_link_mode",
    # repo — discovery
    "discover_albums",
    "discover_browsable_media_files",
    "discover_media_sources",
    "discover_potential_albums",
    "has_media_sources",
    "is_album",
    # repo — file mutations
    "delete_files",
    "move_files",
]
