"""Auto-generate CLI reference documentation from Typer.

Runs `typer photree.cli utils docs` and writes the output to docs/cli-reference.md.
Use --check to verify the docs are up to date.

Usage:
    python build-scripts/clidocs.py          # regenerate docs/cli-reference.md
    python build-scripts/clidocs.py --check  # exit non-zero if out of date
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Annotated

import typer

CLI_REFERENCE_MD = Path("docs/cli-reference.md")
HEADER = "<!-- AUTO-GENERATED by: mise run clidocs — do not edit manually -->"


def _generate_cli_docs() -> str:
    """Run typer utils docs and return the markdown output."""
    result = subprocess.run(
        ["typer", "photree.cli", "utils", "docs", "--name", "photree"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"typer utils docs failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout.rstrip("\n")


def _build_file(generated: str) -> str:
    """Build the full file content with header."""
    return f"{HEADER}\n\n{generated}\n"


app = typer.Typer(add_completion=False)


@app.command()
def main(
    check: Annotated[
        bool,
        typer.Option(
            "--check", help="Check that docs are up to date (exit non-zero if not)"
        ),
    ] = False,
) -> None:
    """Generate or check CLI reference documentation in docs/cli-reference.md."""
    generated = _generate_cli_docs()
    expected = _build_file(generated)

    if check:
        current = CLI_REFERENCE_MD.read_text() if CLI_REFERENCE_MD.exists() else ""
        if current == expected:
            print("CLI reference is up to date.")
        else:
            print(
                f"CLI reference in {CLI_REFERENCE_MD} is out of date.\n"
                "Run `mise run clidocs` to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        CLI_REFERENCE_MD.write_text(expected)
        print(f"Updated {CLI_REFERENCE_MD}")


if __name__ == "__main__":
    app()
