"""Generate a mermaid module dependency graph from pydeps DOT output.

Writes the Module Overview section into docs/architecture.md between markers.
Use --check to verify the docs are up to date. Use --format to print to stdout
instead of updating the file.

Requires: pydeps (dev dependency), graphviz (system: brew install graphviz).

Usage:
    python build-scripts/depgraph.py          # regenerate Module Overview in architecture.md
    python build-scripts/depgraph.py --check  # exit non-zero if out of date
    python build-scripts/depgraph.py --format mermaid  # print to stdout
    python build-scripts/depgraph.py --format ascii    # print ASCII art to stdout
"""

from __future__ import annotations

import enum
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Annotated, Optional

import typer

PACKAGE = "photree"
ARCHITECTURE_MD = Path("docs/architecture.md")
BEGIN_MARKER = "<!-- BEGIN MODULE OVERVIEW (auto-generated by: mise run depgraph — do not edit manually) -->"
END_MARKER = "<!-- END MODULE OVERVIEW -->"


def _is_package(label: str) -> bool:
    """Check if a module label corresponds to a package (directory with __init__.py)."""
    return (Path(PACKAGE) / label / "__init__.py").exists()


def _run_pydeps(package: str = PACKAGE) -> str:
    """Run pydeps and return DOT output."""
    if not shutil.which("dot"):
        print(
            "Error: graphviz is not installed.\n"
            "  macOS:  brew install graphviz\n"
            "  Linux:  apt install graphviz",
            file=sys.stderr,
        )
        sys.exit(1)

    result = subprocess.run(
        [
            "pydeps",
            package,
            "--show-dot",
            "--no-output",
            "--no-show",
            "--max-module-depth",
            "2",
            "--only",
            package,
            "--rmprefix",
            f"{package}.",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"pydeps failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def _dot_to_mermaid(dot: str) -> str:
    """Convert pydeps DOT output to mermaid graph TD syntax.

    pydeps edges point from dependency to dependent (A -> B means "A is used by B"),
    so we reverse them to match the convention "B depends on A" (B --> A).
    """
    # Extract node declarations: node_id [... label="name" ...]
    node_pattern = re.compile(r'^\s+(\w+)\s+\[.*?label="([^"]+)".*?\]', re.MULTILINE)
    nodes: dict[str, str] = {}
    for match in node_pattern.finditer(dot):
        node_id, label = match.group(1), match.group(2)
        nodes[node_id] = label

    # Extract edges: src -> dst
    edge_pattern = re.compile(r"^\s+(\w+)\s+->\s+(\w+)", re.MULTILINE)
    edges: list[tuple[str, str]] = []
    for match in edge_pattern.finditer(dot):
        dep, dependent = match.group(1), match.group(2)
        # Reverse: dependent depends on dep
        edges.append((nodes.get(dependent, dependent), nodes.get(dep, dep)))

    # Build mermaid
    lines = ["graph TD"]

    # Node declarations (sorted for determinism)
    for node_id in sorted(nodes):
        label = nodes[node_id]
        display = f"{label}/" if _is_package(label) else label
        lines.append(f'    {label}["{display}"]')

    lines.append("")

    # Edges (sorted for determinism)
    for src, dst in sorted(edges):
        lines.append(f"    {src} --> {dst}")

    return "\n".join(lines)


def _render_ascii(mermaid_src: str) -> str:
    """Render mermaid to ASCII via mermaid-ascii-diagrams."""
    from mermaid_ascii import parse_mermaid, render_ascii

    diagram = parse_mermaid(mermaid_src)
    return render_ascii(diagram)


def _build_section(mermaid: str) -> str:
    """Build the marker-delimited section content."""
    return (
        f"{BEGIN_MARKER}\n"
        "## Module Overview\n"
        "\n"
        "Dependencies between top-level modules (auto-generated via `mise run depgraph`):\n"
        "```mermaid\n"
        f"{mermaid}\n"
        "```\n"
        f"{END_MARKER}"
    )


def _splice_section(file_content: str, section: str) -> str:
    """Replace content between markers in the file."""
    begin_idx = file_content.find(BEGIN_MARKER)
    end_idx = file_content.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1:
        print(
            f"Error: markers not found in {ARCHITECTURE_MD}.\n"
            f"Expected:\n  {BEGIN_MARKER}\n  {END_MARKER}",
            file=sys.stderr,
        )
        sys.exit(1)
    return (
        file_content[:begin_idx] + section + file_content[end_idx + len(END_MARKER) :]
    )


class GraphFormat(str, enum.Enum):
    """Output format for the dependency graph."""

    MERMAID = "mermaid"
    ASCII = "ascii"


app = typer.Typer(add_completion=False)


@app.command()
def main(
    fmt: Annotated[
        Optional[GraphFormat],
        typer.Option("--format", "-f", help="Print to stdout in this format"),
    ] = None,
    check: Annotated[
        bool,
        typer.Option(
            "--check",
            help="Check that Module Overview in architecture.md is up to date (exit non-zero if not)",
        ),
    ] = False,
) -> None:
    """Generate a module dependency graph from pydeps analysis."""
    dot = _run_pydeps()
    mermaid = _dot_to_mermaid(dot)

    # --format: print to stdout and exit
    if fmt is not None:
        match fmt:
            case GraphFormat.MERMAID:
                print(mermaid)
            case GraphFormat.ASCII:
                print(_render_ascii(mermaid))
        return

    # Default: update architecture.md (or --check)
    section = _build_section(mermaid)
    current = ARCHITECTURE_MD.read_text() if ARCHITECTURE_MD.exists() else ""
    expected = _splice_section(current, section)

    if check:
        if current == expected:
            print("Module Overview in architecture.md is up to date.")
        else:
            print(
                f"Module Overview in {ARCHITECTURE_MD} is out of date.\n"
                "Run `mise run depgraph` to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        ARCHITECTURE_MD.write_text(expected)
        print(f"Updated Module Overview in {ARCHITECTURE_MD}")


if __name__ == "__main__":
    app()
