name: demo

on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - main
  # Tags created by a workflow using GITHUB_TOKEN do not trigger other workflows,
  # so we use workflow_run to run the demo after the release workflow creates a tag.
  workflow_run:
    workflows: ["release"]
    types:
      - completed
  # Manually trigger the workflow using
  # gh workflow run demo.yml # --ref <branch>
  # gh run list --workflow demo.yml # --branch <branch>
  workflow_dispatch:
  repository_dispatch:
  # pull_request:

concurrency:
  # On main/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('{0}-main-{1}', github.workflow, github.sha) || format('{0}-main-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true
  HAS_ASCIINEMA_INSTALL_ID: ${{ secrets.ASCIINEMA_INSTALL_ID != '' }}

jobs:
  demo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: jdx/mise-action@v4
      - name: Install pv (required by demo-magic)
        run: sudo apt-get update && sudo apt-get install -y pv
      - name: Record demo
        run: mise run ci-demo-record
      - name: Set up asciinema install ID
        if: env.HAS_ASCIINEMA_INSTALL_ID == 'true'
        env:
          ASCIINEMA_INSTALL_ID: ${{ secrets.ASCIINEMA_INSTALL_ID }}
        run: |
          mkdir -p "$HOME/.local/state/asciinema"
          echo "$ASCIINEMA_INSTALL_ID" > "$HOME/.local/state/asciinema/install-id"
      - name: Upload demo
        # Trigger on release workflow runs or on tag pushes
        if: >-
          startsWith(github.ref, 'refs/tags/')
          || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
          || github.event_name == 'workflow_dispatch'
          || github.event_name == 'repository_dispatch'

        env:
          ASCIINEMA_SERVER_URL: https://asciinema.org
        run: mise run demo-upload
